### ISSUE TITLE
Forgetting to include a servicer leads to a bad stack trace when trying to do a query

### ISSUE THREAD

**Issue by benh** [reboot-dev/pyprotoc-plugin#36]
```
ERROR:grpc._cython.cygrpc:Unexpected [KeyError] raised by servicer method [/resemble.v1alpha1.React/Query]
Traceback (most recent call last):
  File "external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 682, in _cython.cygrpc._handle_exceptions
  File "external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 803, in _handle_rpc
  File "external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 580, in _handle_unary_stream_rpc
  File "external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 495, in _finish_handler_with_stream_responses
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble/aio/react.py", line 46, in Query
    async for (response, idempotency_keys) in middleware.react(
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble_react_example/api/pingpong_rsm.py", line 177, in react
    response = await self._servicer.Ping(
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble_react_example/backend/pingpong_servicer.py", line 30, in Ping
    response = await random.Get(context)
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble_react_example/api/pingpong_rsm.py", line 2073, in Get
    return await self.reader(context).Get(
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble_react_example/api/pingpong_rsm.py", line 2020, in reader
    self._reader_stub = RandomReaderStub(
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble_react_example/api/pingpong_rsm.py", line 1494, in __init__
    super().__init__(context_or_workflow, actor_id)
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble_react_example/api/pingpong_rsm.py", line 1477, in __init__
    channel = self._channel_manager.get_channel_for(
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble/aio/internals/channel_manager.py", line 47, in get_channel_for
    return self.get_channel_from_service_name(
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble/aio/internals/channel_manager.py", line 37, in get_channel_from_service_name
    self._resolver.resolve_actor(service_name, actor_id)
  File "/tmp/Bazel.runfiles_p5gunk5s/runfiles/com_github_reboot_dev_respect/resemble/aio/resolvers.py", line 210, in resolve_actor
    consensus_name = self._consensus_by_service[service_name]
KeyError: 'resemble_react_example.api.Random'
```

**Comment by benh** [comment]
This was an accidentally created issue in this repository. It's closed by https://github.com/reboot-dev/respect/pull/2065. Closing here now.
